# Generated by Django 6.1.1 on 2026-09-14 22:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Início')),
                ('end_datetime', models.DateTimeField(verbose_name='Fim')),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada'), ('EM_ATENDIMENTO', 'Em atendimento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('FALTA', 'Falta')], default='AGENDADA', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Telefone deve estar em formato válido.', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias')),
                ('medications', models.TextField(blank=True, verbose_name='Medicações em uso')),
                ('health_conditions', models.TextField(blank=True, verbose_name='Condições de saúde relevantes')),
                ('has_insurance', models.BooleanField(default=False, verbose_name='Possui convênio')),
                ('insurance_name', models.CharField(blank=True, max_length=100)),
                ('insurance_number', models.CharField(blank=True, max_length=50)),
                ('consent_data_processing', models.BooleanField(default=False, verbose_name='Consentimento LGPD')),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do procedimento')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Código (TUSS/tabela própria)')),
                ('description', models.TextField(blank=True)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_duration', models.PositiveIntegerField(default=30, verbose_name='Duração estimada (min)')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição do atendimento')),
                ('prescription', models.TextField(blank=True, verbose_name='Prescrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_note', to='core.appointment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anotação clínica',
                'verbose_name_plural': 'Anotações clínicas',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='core.patient')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.patient'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('PIX', 'Pix'), ('CONVENIO', 'Convênio')], max_length=20)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('installment_number', models.PositiveIntegerField(default=1)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.budget')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.budget')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.procedure')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.procedure'),
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cro', models.CharField(max_length=20, unique=True, verbose_name='CRO')),
                ('cro_state', models.CharField(max_length=2, verbose_name='UF do CRO')),
                ('specialty', models.CharField(choices=[('GERAL', 'Clínico Geral'), ('ORTO', 'Ortodontia'), ('ENDO', 'Endodontia'), ('IMPL', 'Implantodontia'), ('PERIO', 'Periodontia'), ('PEDO', 'Odontopediatria'), ('CIR', 'Cirurgia Bucomaxilofacial')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'permissions': [('view_all_agendas', 'Pode visualizar agenda de todos os profissionais'), ('manage_financeiro', 'Pode gerenciar módulo financeiro')],
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='core.professional'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.professional'),
        ),
        migrations.CreateModel(
            name='ToothCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.PositiveSmallIntegerField(verbose_name='Número do dente (FDI)')),
                ('condition', models.CharField(choices=[('SAUDAVEL', 'Saudável'), ('CARIE', 'Cárie'), ('RESTAURADO', 'Restaurado'), ('EXTRAIDO', 'Extraído'), ('IMPLANTE', 'Implante'), ('CANAL', 'Tratamento de canal'), ('COROA', 'Coroa')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tooth_records', to='core.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_records', to='core.patient')),
            ],
            options={
                'verbose_name': 'Registro dentário',
                'verbose_name_plural': 'Odontograma',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='appointment_end_after_start'),
        ),
    ]
